### ISSUE TITLE
Need a way to delete samples

### ISSUE THREAD

**Issue by naught101** [harryhaaren/openAV-Fabla#27]
There doesn't appear to be a way to remove samples, except by overwriting them with a new sample. A way to delete samples from a kit would be useful.

**Comment by harryhaaren** [comment]
Closing issue: Fabla2, which is a [work in progress, see here](https://github.com/harryhaaren/openAV-Fabla/wiki) can remove samples. Fabla 1 will not have this feature implemented.

Cheers, -Harry
