### ISSUE TITLE
Automatic resampling samples to host's sample rate on load

### ISSUE THREAD

**Issue by danvd** [harryhaaren/openAV-Fabla#40]
Hi,  Harry!

It will be just great to support make in-memory resampling when loading samples in Fabla. Now if jack (and host) is running in, for example, 96 kHz, and some drum sample is in 48 kHz, it will be played 2x times faster, depending on slected host's sample rate. Non-destructive in-memory resampling on sample load will make it a lot easier to manage sound files and will avoid resampling them by hand for every project with different base sample rate.

Thanks.

**Comment by harryhaaren** [comment]
Hi Andrew,

This is already implemented + working in Fabla2. I won't fix this in Fabla1 as its going to be made redundant Fabla2, and I'd prefer put my energy into finishing Fabla2.

Thanks for the request, and noted that this is something that should be handled gracefully.
Cheers, -Harry

**Comment by danvd** [comment]
Hi Harry,

Thanks for quick answer. Honestly, before your message I thought, that Fabla 2 is only in plans now :).
Just interesting: Do you plan to make F2 available to public (and when)?

Regards,
Andrew

**Comment by harryhaaren** [comment]
Nope, Fabla2 is alive, running and in very active development:
Checkout the status on [the OpenAV Fabla2 page](http://openavproductions.com/fabla2)
or the per-feature status on [the Fabla Wiki](https://github.com/harryhaaren/openAV-Fabla/wiki).

Yes it will be released publicly, once it is stable and has passed beta testing. Right now its *almost* in feature-freeze for 2.0-beta1,  I really hope to release in the next weeks if at all possible.

**Comment by danvd** [comment]
Thanks!

I have nothing more to ask, really :)

**Comment by ViktorNova** [comment]
Exciting that it so close! 
I'm hereby volunteering to help beta test if you want help, I'll hit it with everything I got =)
