### ISSUE TITLE
Fabla is somehow sucking the punch out of my samples

### ISSUE THREAD

**Issue by ViktorNova** [harryhaaren/openAV-Fabla#42]
I've been banging my head against the wall for months trying to get my band's beats sounding as good through Fabla as they did in Hydrogen.. Since the MIDI hasn't changed, I figured it was just a matter of getting the levels in Fabla set just right, but today I realized that the same samples actually sound quite noticeably different through Fabla, much more dull (very noticeable in my kick samples, they seem to have no "click" in Fabla)

Yesterday it occurred to me that that Fabla isn't re-sampling, so I resampled my whole collection so they'd all be correct, but they are still sounding dull only through Fabla.

I was able to approximate the same dulling effect in Hydrogen by turning the attack up to maximum..
Is Fabla forcibly adding attack to all samples, or are you aware of anything else that might be causing this?

I did notice that the envelope appears to have a permanent slope on the front, although I always assumed that was only decorative..(it would certainly explain what's  happening though)

**Comment by harryhaaren** [comment]
@ViktorNova could you send me one of the samples please? It would help both in finding a possible bug / issue, and in verifying the fix after fixing.

Yes Fabla (and every other sampler worth its salt) adds an attack envelope to the sample playback - this is necessary to avoid "clicks" in the audio output if the sample starts with DC offset, or at a non-zero sample value.

The issue might be that Fabla is actually adding too much attack -  I'll investigate this with playing back your sample and doing some analysis of the raw sample vs the played back one.

Cheers, -Harry

**Comment by harryhaaren** [comment]
I've reduced the minimum attack amount, please test this version - if a sample has a large DC offset, then it may cause a click - that said, the click is in the sample, so perhaps its what you want :)

In terms of maximum punch, compression generally reduces perceived punch as the main body of the sound becomes louder relative to the attack stage. Right-clicking the compressor enable/disables it, so perhaps check if its the compressor that is causing part of this.

Cheers, -Harry

**Comment by ViktorNova** [comment]
WOW that was fast! 
It is a night and day difference, the samples in Fabla are now indiscernible from the original, and the life has come back into my tracks. =D

Thanks a bunch! 
Out of pure curiosity, how many milliseconds is the attack now?

**Comment by harryhaaren** [comment]
Now Its 2 ms, it used to be 10ms. Thanks for the feedback, and thanks for supporting OpenAV! Cheers, -Harry

**Comment by ViktorNova** [comment]
Sorry to bug you about this again..I never would have guessed 10ms (and much less, 2ms) would make this much of a difference, but on a few samples it is actually still quite noticeable - I've attached a sample so you can hear it for yourself (needs to be renamed to .wav since GitHub doesn't allow attaching sound files) You may need to crank it to a chest-bumping volume for the difference to be obvious

![kick -hi cache wav](https://cloud.githubusercontent.com/assets/3234333/6520691/116ed324-c37f-11e4-97d9-85e3a938ef59.jpg)
![kick -hi cache 2ms wav](https://cloud.githubusercontent.com/assets/3234333/6520690/116edb94-c37f-11e4-8d0a-8bfaadd9e866.jpg)

The 2 samples are identical, except I added approx 2ms of silence to the beginning of one of the two, and they sound quite different (interestingly, the tail of the 2 samples seem to sound a little different too, almost as if there is a DC click on the one *without* the silence in the beginning..which makes no sense, might just be a mind trick)

How do you feel about removing the enforced attack altogether? My reasoning is that any professional sample pack will already have all of their samples with a zero DC offset, and anyone producing their own samples or using a drum sampler in any serious capacity will know to do this to their samples as part of the process, anyhow at the very least there should be an option to disable it

I know you're focusing on Fabla 2 (and I definitely don't want to take away from that!) so maybe a good compromise for Fabla 1 would be to take the 2ms attack down to zero only when the envelope is disabled..what do you think? =)
