### ISSUE TITLE
OpenGL headers are required but not mentioned in dependencies list

### ISSUE THREAD

**Issue by jessecrossen** [harryhaaren/openAV-Fabla#43]
I got the following when compiling on Ubuntu 15.04:

```
~/Documents/openav/openAV-Fabla/build$ make
[ 16%] Building CXX object CMakeFiles/fabla.dir/gui/fabla.cxx.o
In file included from /home/jesse/Documents/openav/openAV-Fabla/gui/avtk/avtk_opengl.h:28:0,
                 from /home/jesse/Documents/openav/openAV-Fabla/gui/avtk.h:32,
                 from /home/jesse/Documents/openav/openAV-Fabla/gui/fabla.h:7,
                 from /home/jesse/Documents/openav/openAV-Fabla/gui/fabla.cxx:3:
/usr/local/include/ntk/FL/gl.h:69:23: fatal error: GL/gl.h: No such file or directory
 #    include <GL/gl.h>
```

This is resolved by running `sudo apt-get install mesa-common-dev`, but I think it should be mentioned as a dependency. I see the relevant file is in the ntk headers, but ntk installed fine without opengl, so maybe the dependency should be mentioned in this project's docs.

**Comment by harryhaaren** [comment]
Hi @jessecrossen,

Yes you're right - when NTK is built with --enable-gl, the headers must be in place. Given that Fabla doesn't directly include GL itself, and doesn't require NTK to be built with GL enabled, I'm not sure its needed to be listed as a dep of Fabla though?

Thanks for posting this as an issue though - in future if anybody searches the error, then they'll see this and see your fix:
```
sudo apt-get install mesa-common-dev
```

Thanks, -Harry
